version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21

  pre_build:
    commands:
      - echo Running Go tests...
      - go test -v ./...
      - echo Logging in to Docker registry...
      - echo $DOCKER_PASSWORD | docker login git.systementor.se -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t git.systementor.se/olena/stensax .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push git.systementor.se/olena/stensax
    



# Rebuild image locally
# docker buildx build --platform linux/amd64 -t git.systementor.se/olena/stensax .

# Push with buildx (especially important on M1/M2 Macs)
# docker buildx build --platform linux/amd64 -t git.systementor.se/olena/stensax --push .
